name: Windows Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  windows_wheel:
    continue-on-error: true
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.6.8, 3.7.9, 3.8.8, 3.9.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install choco packages
        run: |
           choco install 7zip wget
           choco install --version ${{ matrix.python-version }} python

      - name: Upgrade pip and wheel for all pythons
        run:  python.exe -m pip install --upgrade pip wheel

      - name: Install python libraries
        run: python.exe -m pip install .[test]

      - name: Run tests
        run: pytest.exe

      - name: Run binary wheel
        run: python.exe setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        name: Publish binary wheels
        with:
          path: dist/*.whl
